// Pumat wire protocol, v1 (spec §7.4, §15, §16).
//
// Every signed object travels as a SignedEnvelope whose payload is RFC 8785
// canonical JSON; protobuf is framing only and is never signed or hashed.
// Frames are length-delimited (varint size prefix) on libp2p streams.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: pumat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignedEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        string                 `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signatures    []*Signature           `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedEnvelope) Reset() {
	*x = SignedEnvelope{}
	mi := &file_pumat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedEnvelope) ProtoMessage() {}

func (x *SignedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedEnvelope.ProtoReflect.Descriptor instead.
func (*SignedEnvelope) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{0}
}

func (x *SignedEnvelope) GetSchema() string {
	if x != nil {
		return x.Schema
	}
	return ""
}

func (x *SignedEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedEnvelope) GetSignatures() []*Signature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signer        string                 `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Alg           string                 `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	Sig           []byte                 `protobuf:"bytes,3,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_pumat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{1}
}

func (x *Signature) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

func (x *Signature) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

func (x *Signature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_pumat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Frame_Error
	//	*Frame_CapabilityRequest
	//	*Frame_Capability
	//	*Frame_LeaseRequest
	//	*Frame_LeaseOffer
	//	*Frame_LeaseCountersigned
	//	*Frame_LeaseConfirm
	//	*Frame_InputBegin
	//	*Frame_InputHave
	//	*Frame_Chunk
	//	*Frame_InputDone
	//	*Frame_StatusRequest
	//	*Frame_Status
	//	*Frame_ChunkRequest
	//	*Frame_Ack
	//	*Frame_AckResult
	//	*Frame_RecordRequest
	//	*Frame_RecordManifest
	//	*Frame_Announcement
	//	*Frame_Cancel
	Body          isFrame_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_pumat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{3}
}

func (x *Frame) GetBody() isFrame_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Frame) GetError() *Error {
	if x != nil {
		if x, ok := x.Body.(*Frame_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Frame) GetCapabilityRequest() *CapabilityRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_CapabilityRequest); ok {
			return x.CapabilityRequest
		}
	}
	return nil
}

func (x *Frame) GetCapability() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Body.(*Frame_Capability); ok {
			return x.Capability
		}
	}
	return nil
}

func (x *Frame) GetLeaseRequest() *LeaseRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_LeaseRequest); ok {
			return x.LeaseRequest
		}
	}
	return nil
}

func (x *Frame) GetLeaseOffer() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Body.(*Frame_LeaseOffer); ok {
			return x.LeaseOffer
		}
	}
	return nil
}

func (x *Frame) GetLeaseCountersigned() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Body.(*Frame_LeaseCountersigned); ok {
			return x.LeaseCountersigned
		}
	}
	return nil
}

func (x *Frame) GetLeaseConfirm() *LeaseConfirm {
	if x != nil {
		if x, ok := x.Body.(*Frame_LeaseConfirm); ok {
			return x.LeaseConfirm
		}
	}
	return nil
}

func (x *Frame) GetInputBegin() *InputBegin {
	if x != nil {
		if x, ok := x.Body.(*Frame_InputBegin); ok {
			return x.InputBegin
		}
	}
	return nil
}

func (x *Frame) GetInputHave() *InputHave {
	if x != nil {
		if x, ok := x.Body.(*Frame_InputHave); ok {
			return x.InputHave
		}
	}
	return nil
}

func (x *Frame) GetChunk() *Chunk {
	if x != nil {
		if x, ok := x.Body.(*Frame_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *Frame) GetInputDone() *InputDone {
	if x != nil {
		if x, ok := x.Body.(*Frame_InputDone); ok {
			return x.InputDone
		}
	}
	return nil
}

func (x *Frame) GetStatusRequest() *StatusRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_StatusRequest); ok {
			return x.StatusRequest
		}
	}
	return nil
}

func (x *Frame) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Body.(*Frame_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Frame) GetChunkRequest() *ChunkRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_ChunkRequest); ok {
			return x.ChunkRequest
		}
	}
	return nil
}

func (x *Frame) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Body.(*Frame_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Frame) GetAckResult() *AckResult {
	if x != nil {
		if x, ok := x.Body.(*Frame_AckResult); ok {
			return x.AckResult
		}
	}
	return nil
}

func (x *Frame) GetRecordRequest() *RecordRequest {
	if x != nil {
		if x, ok := x.Body.(*Frame_RecordRequest); ok {
			return x.RecordRequest
		}
	}
	return nil
}

func (x *Frame) GetRecordManifest() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Body.(*Frame_RecordManifest); ok {
			return x.RecordManifest
		}
	}
	return nil
}

func (x *Frame) GetAnnouncement() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Body.(*Frame_Announcement); ok {
			return x.Announcement
		}
	}
	return nil
}

func (x *Frame) GetCancel() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Body.(*Frame_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isFrame_Body interface {
	isFrame_Body()
}

type Frame_Error struct {
	Error *Error `protobuf:"bytes,1,opt,name=error,proto3,oneof"`
}

type Frame_CapabilityRequest struct {
	CapabilityRequest *CapabilityRequest `protobuf:"bytes,2,opt,name=capability_request,json=capabilityRequest,proto3,oneof"`
}

type Frame_Capability struct {
	Capability *SignedEnvelope `protobuf:"bytes,3,opt,name=capability,proto3,oneof"`
}

type Frame_LeaseRequest struct {
	LeaseRequest *LeaseRequest `protobuf:"bytes,4,opt,name=lease_request,json=leaseRequest,proto3,oneof"`
}

type Frame_LeaseOffer struct {
	LeaseOffer *SignedEnvelope `protobuf:"bytes,5,opt,name=lease_offer,json=leaseOffer,proto3,oneof"` // worker-signed lease draft
}

type Frame_LeaseCountersigned struct {
	LeaseCountersigned *SignedEnvelope `protobuf:"bytes,6,opt,name=lease_countersigned,json=leaseCountersigned,proto3,oneof"` // requester + worker signatures
}

type Frame_LeaseConfirm struct {
	LeaseConfirm *LeaseConfirm `protobuf:"bytes,7,opt,name=lease_confirm,json=leaseConfirm,proto3,oneof"`
}

type Frame_InputBegin struct {
	InputBegin *InputBegin `protobuf:"bytes,8,opt,name=input_begin,json=inputBegin,proto3,oneof"`
}

type Frame_InputHave struct {
	InputHave *InputHave `protobuf:"bytes,9,opt,name=input_have,json=inputHave,proto3,oneof"`
}

type Frame_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,10,opt,name=chunk,proto3,oneof"`
}

type Frame_InputDone struct {
	InputDone *InputDone `protobuf:"bytes,11,opt,name=input_done,json=inputDone,proto3,oneof"`
}

type Frame_StatusRequest struct {
	StatusRequest *StatusRequest `protobuf:"bytes,12,opt,name=status_request,json=statusRequest,proto3,oneof"`
}

type Frame_Status struct {
	Status *Status `protobuf:"bytes,13,opt,name=status,proto3,oneof"`
}

type Frame_ChunkRequest struct {
	ChunkRequest *ChunkRequest `protobuf:"bytes,14,opt,name=chunk_request,json=chunkRequest,proto3,oneof"`
}

type Frame_Ack struct {
	Ack *Ack `protobuf:"bytes,15,opt,name=ack,proto3,oneof"`
}

type Frame_AckResult struct {
	AckResult *AckResult `protobuf:"bytes,16,opt,name=ack_result,json=ackResult,proto3,oneof"`
}

type Frame_RecordRequest struct {
	RecordRequest *RecordRequest `protobuf:"bytes,17,opt,name=record_request,json=recordRequest,proto3,oneof"`
}

type Frame_RecordManifest struct {
	RecordManifest *SignedEnvelope `protobuf:"bytes,18,opt,name=record_manifest,json=recordManifest,proto3,oneof"` // pumat.record.v1, publisher-signed
}

type Frame_Announcement struct {
	Announcement *SignedEnvelope `protobuf:"bytes,19,opt,name=announcement,proto3,oneof"` // pumat.publication.v1
}

type Frame_Cancel struct {
	Cancel *SignedEnvelope `protobuf:"bytes,20,opt,name=cancel,proto3,oneof"` // pumat.cancel.v1, requester-signed (on /pumat/result)
}

func (*Frame_Error) isFrame_Body() {}

func (*Frame_CapabilityRequest) isFrame_Body() {}

func (*Frame_Capability) isFrame_Body() {}

func (*Frame_LeaseRequest) isFrame_Body() {}

func (*Frame_LeaseOffer) isFrame_Body() {}

func (*Frame_LeaseCountersigned) isFrame_Body() {}

func (*Frame_LeaseConfirm) isFrame_Body() {}

func (*Frame_InputBegin) isFrame_Body() {}

func (*Frame_InputHave) isFrame_Body() {}

func (*Frame_Chunk) isFrame_Body() {}

func (*Frame_InputDone) isFrame_Body() {}

func (*Frame_StatusRequest) isFrame_Body() {}

func (*Frame_Status) isFrame_Body() {}

func (*Frame_ChunkRequest) isFrame_Body() {}

func (*Frame_Ack) isFrame_Body() {}

func (*Frame_AckResult) isFrame_Body() {}

func (*Frame_RecordRequest) isFrame_Body() {}

func (*Frame_RecordManifest) isFrame_Body() {}

func (*Frame_Announcement) isFrame_Body() {}

func (*Frame_Cancel) isFrame_Body() {}

// /pumat/capability/1.0.0
type CapabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRequest) Reset() {
	*x = CapabilityRequest{}
	mi := &file_pumat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRequest) ProtoMessage() {}

func (x *CapabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRequest.ProtoReflect.Descriptor instead.
func (*CapabilityRequest) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// /pumat/lease/1.0.0
type LeaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Request        *SignedEnvelope        `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`                                     // pumat.lease.request.v1, requester-signed
	SolverManifest *SignedEnvelope        `protobuf:"bytes,2,opt,name=solver_manifest,json=solverManifest,proto3" json:"solver_manifest,omitempty"` // pumat.solver.v1, trust-root-signed
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseRequest) Reset() {
	*x = LeaseRequest{}
	mi := &file_pumat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRequest) ProtoMessage() {}

func (x *LeaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRequest.ProtoReflect.Descriptor instead.
func (*LeaseRequest) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{5}
}

func (x *LeaseRequest) GetRequest() *SignedEnvelope {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *LeaseRequest) GetSolverManifest() *SignedEnvelope {
	if x != nil {
		return x.SolverManifest
	}
	return nil
}

type LeaseConfirm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaseId       string                 `protobuf:"bytes,1,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseConfirm) Reset() {
	*x = LeaseConfirm{}
	mi := &file_pumat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseConfirm) ProtoMessage() {}

func (x *LeaseConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseConfirm.ProtoReflect.Descriptor instead.
func (*LeaseConfirm) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{6}
}

func (x *LeaseConfirm) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// /pumat/input/1.0.0
type InputBegin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ChunkSize     uint32                 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkHashes   [][]byte               `protobuf:"bytes,4,rep,name=chunk_hashes,json=chunkHashes,proto3" json:"chunk_hashes,omitempty"` // leaf hashes; root must equal lease input_bundle_digest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputBegin) Reset() {
	*x = InputBegin{}
	mi := &file_pumat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputBegin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputBegin) ProtoMessage() {}

func (x *InputBegin) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputBegin.ProtoReflect.Descriptor instead.
func (*InputBegin) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{7}
}

func (x *InputBegin) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *InputBegin) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InputBegin) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *InputBegin) GetChunkHashes() [][]byte {
	if x != nil {
		return x.ChunkHashes
	}
	return nil
}

type InputHave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Missing       []uint32               `protobuf:"varint,1,rep,packed,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputHave) Reset() {
	*x = InputHave{}
	mi := &file_pumat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputHave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputHave) ProtoMessage() {}

func (x *InputHave) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputHave.ProtoReflect.Descriptor instead.
func (*InputHave) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{8}
}

func (x *InputHave) GetMissing() []uint32 {
	if x != nil {
		return x.Missing
	}
	return nil
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"` // set on the final chunk of a record file stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_pumat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{9}
}

func (x *Chunk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chunk) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type InputDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputDone) Reset() {
	*x = InputDone{}
	mi := &file_pumat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputDone) ProtoMessage() {}

func (x *InputDone) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputDone.ProtoReflect.Descriptor instead.
func (*InputDone) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{10}
}

func (x *InputDone) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// /pumat/result/1.0.0
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_pumat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{11}
}

func (x *StatusRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

type Status struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ExecId                string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	State                 string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Completion            *SignedEnvelope        `protobuf:"bytes,3,opt,name=completion,proto3" json:"completion,omitempty"` // set from SEALED on
	Enc                   []byte                 `protobuf:"bytes,4,opt,name=enc,proto3" json:"enc,omitempty"`               // HPKE encapsulated key
	SealedSize            int64                  `protobuf:"varint,5,opt,name=sealed_size,json=sealedSize,proto3" json:"sealed_size,omitempty"`
	SealedChunkSize       uint32                 `protobuf:"varint,6,opt,name=sealed_chunk_size,json=sealedChunkSize,proto3" json:"sealed_chunk_size,omitempty"`
	SealedChunkHashes     [][]byte               `protobuf:"bytes,7,rep,name=sealed_chunk_hashes,json=sealedChunkHashes,proto3" json:"sealed_chunk_hashes,omitempty"`
	ElapsedSeconds        int64                  `protobuf:"varint,8,opt,name=elapsed_seconds,json=elapsedSeconds,proto3" json:"elapsed_seconds,omitempty"`
	RetentionDeadlineUnix int64                  `protobuf:"varint,9,opt,name=retention_deadline_unix,json=retentionDeadlineUnix,proto3" json:"retention_deadline_unix,omitempty"`
	Message               string                 `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_pumat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{12}
}

func (x *Status) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *Status) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Status) GetCompletion() *SignedEnvelope {
	if x != nil {
		return x.Completion
	}
	return nil
}

func (x *Status) GetEnc() []byte {
	if x != nil {
		return x.Enc
	}
	return nil
}

func (x *Status) GetSealedSize() int64 {
	if x != nil {
		return x.SealedSize
	}
	return 0
}

func (x *Status) GetSealedChunkSize() uint32 {
	if x != nil {
		return x.SealedChunkSize
	}
	return 0
}

func (x *Status) GetSealedChunkHashes() [][]byte {
	if x != nil {
		return x.SealedChunkHashes
	}
	return nil
}

func (x *Status) GetElapsedSeconds() int64 {
	if x != nil {
		return x.ElapsedSeconds
	}
	return 0
}

func (x *Status) GetRetentionDeadlineUnix() int64 {
	if x != nil {
		return x.RetentionDeadlineUnix
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChunkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecId        string                 `protobuf:"bytes,1,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	Indices       []uint32               `protobuf:"varint,2,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkRequest) Reset() {
	*x = ChunkRequest{}
	mi := &file_pumat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkRequest) ProtoMessage() {}

func (x *ChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkRequest.ProtoReflect.Descriptor instead.
func (*ChunkRequest) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{13}
}

func (x *ChunkRequest) GetExecId() string {
	if x != nil {
		return x.ExecId
	}
	return ""
}

func (x *ChunkRequest) GetIndices() []uint32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acceptance    *SignedEnvelope        `protobuf:"bytes,1,opt,name=acceptance,proto3" json:"acceptance,omitempty"` // pumat.receipt.acceptance.v1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_pumat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{14}
}

func (x *Ack) GetAcceptance() *SignedEnvelope {
	if x != nil {
		return x.Acceptance
	}
	return nil
}

type AckResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResult) Reset() {
	*x = AckResult{}
	mi := &file_pumat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResult) ProtoMessage() {}

func (x *AckResult) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResult.ProtoReflect.Descriptor instead.
func (*AckResult) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{15}
}

func (x *AckResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// /pumat/record/1.0.0 (§24): path "" returns the manifest; otherwise the
// file is streamed as Chunk frames ending with last=true.
type RecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordRequest) Reset() {
	*x = RecordRequest{}
	mi := &file_pumat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordRequest) ProtoMessage() {}

func (x *RecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pumat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordRequest.ProtoReflect.Descriptor instead.
func (*RecordRequest) Descriptor() ([]byte, []int) {
	return file_pumat_proto_rawDescGZIP(), []int{16}
}

func (x *RecordRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *RecordRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_pumat_proto protoreflect.FileDescriptor

const file_pumat_proto_rawDesc = "" +
	"\n" +
	"\vpumat.proto\x12\bpumat.v1\"w\n" +
	"\x0eSignedEnvelope\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\tR\x06schema\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x123\n" +
	"\n" +
	"signatures\x18\x03 \x03(\v2\x13.pumat.v1.SignatureR\n" +
	"signatures\"G\n" +
	"\tSignature\x12\x16\n" +
	"\x06signer\x18\x01 \x01(\tR\x06signer\x12\x10\n" +
	"\x03alg\x18\x02 \x01(\tR\x03alg\x12\x10\n" +
	"\x03sig\x18\x03 \x01(\fR\x03sig\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x99\t\n" +
	"\x05Frame\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\x0f.pumat.v1.ErrorH\x00R\x05error\x12L\n" +
	"\x12capability_request\x18\x02 \x01(\v2\x1b.pumat.v1.CapabilityRequestH\x00R\x11capabilityRequest\x12:\n" +
	"\n" +
	"capability\x18\x03 \x01(\v2\x18.pumat.v1.SignedEnvelopeH\x00R\n" +
	"capability\x12=\n" +
	"\rlease_request\x18\x04 \x01(\v2\x16.pumat.v1.LeaseRequestH\x00R\fleaseRequest\x12;\n" +
	"\vlease_offer\x18\x05 \x01(\v2\x18.pumat.v1.SignedEnvelopeH\x00R\n" +
	"leaseOffer\x12K\n" +
	"\x13lease_countersigned\x18\x06 \x01(\v2\x18.pumat.v1.SignedEnvelopeH\x00R\x12leaseCountersigned\x12=\n" +
	"\rlease_confirm\x18\a \x01(\v2\x16.pumat.v1.LeaseConfirmH\x00R\fleaseConfirm\x127\n" +
	"\vinput_begin\x18\b \x01(\v2\x14.pumat.v1.InputBeginH\x00R\n" +
	"inputBegin\x124\n" +
	"\n" +
	"input_have\x18\t \x01(\v2\x13.pumat.v1.InputHaveH\x00R\tinputHave\x12'\n" +
	"\x05chunk\x18\n" +
	" \x01(\v2\x0f.pumat.v1.ChunkH\x00R\x05chunk\x124\n" +
	"\n" +
	"input_done\x18\v \x01(\v2\x13.pumat.v1.InputDoneH\x00R\tinputDone\x12@\n" +
	"\x0estatus_request\x18\f \x01(\v2\x17.pumat.v1.StatusRequestH\x00R\rstatusRequest\x12*\n" +
	"\x06status\x18\r \x01(\v2\x10.pumat.v1.StatusH\x00R\x06status\x12=\n" +
	"\rchunk_request\x18\x0e \x01(\v2\x16.pumat.v1.ChunkRequestH\x00R\fchunkRequest\x12!\n" +
	"\x03ack\x18\x0f \x01(\v2\r.pumat.v1.AckH\x00R\x03ack\x124\n" +
	"\n" +
	"ack_result\x18\x10 \x01(\v2\x13.pumat.v1.AckResultH\x00R\tackResult\x12@\n" +
	"\x0erecord_request\x18\x11 \x01(\v2\x17.pumat.v1.RecordRequestH\x00R\rrecordRequest\x12C\n" +
	"\x0frecord_manifest\x18\x12 \x01(\v2\x18.pumat.v1.SignedEnvelopeH\x00R\x0erecordManifest\x12>\n" +
	"\fannouncement\x18\x13 \x01(\v2\x18.pumat.v1.SignedEnvelopeH\x00R\fannouncement\x122\n" +
	"\x06cancel\x18\x14 \x01(\v2\x18.pumat.v1.SignedEnvelopeH\x00R\x06cancelB\x06\n" +
	"\x04body\"1\n" +
	"\x11CapabilityRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"\x85\x01\n" +
	"\fLeaseRequest\x122\n" +
	"\arequest\x18\x01 \x01(\v2\x18.pumat.v1.SignedEnvelopeR\arequest\x12A\n" +
	"\x0fsolver_manifest\x18\x02 \x01(\v2\x18.pumat.v1.SignedEnvelopeR\x0esolverManifest\")\n" +
	"\fLeaseConfirm\x12\x19\n" +
	"\blease_id\x18\x01 \x01(\tR\aleaseId\"{\n" +
	"\n" +
	"InputBegin\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\rR\tchunkSize\x12!\n" +
	"\fchunk_hashes\x18\x04 \x03(\fR\vchunkHashes\"%\n" +
	"\tInputHave\x12\x18\n" +
	"\amissing\x18\x01 \x03(\rR\amissing\"E\n" +
	"\x05Chunk\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"\x1b\n" +
	"\tInputDone\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"(\n" +
	"\rStatusRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\"\xfb\x02\n" +
	"\x06Status\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x128\n" +
	"\n" +
	"completion\x18\x03 \x01(\v2\x18.pumat.v1.SignedEnvelopeR\n" +
	"completion\x12\x10\n" +
	"\x03enc\x18\x04 \x01(\fR\x03enc\x12\x1f\n" +
	"\vsealed_size\x18\x05 \x01(\x03R\n" +
	"sealedSize\x12*\n" +
	"\x11sealed_chunk_size\x18\x06 \x01(\rR\x0fsealedChunkSize\x12.\n" +
	"\x13sealed_chunk_hashes\x18\a \x03(\fR\x11sealedChunkHashes\x12'\n" +
	"\x0felapsed_seconds\x18\b \x01(\x03R\x0eelapsedSeconds\x126\n" +
	"\x17retention_deadline_unix\x18\t \x01(\x03R\x15retentionDeadlineUnix\x12\x18\n" +
	"\amessage\x18\n" +
	" \x01(\tR\amessage\"A\n" +
	"\fChunkRequest\x12\x17\n" +
	"\aexec_id\x18\x01 \x01(\tR\x06execId\x12\x18\n" +
	"\aindices\x18\x02 \x03(\rR\aindices\"?\n" +
	"\x03Ack\x128\n" +
	"\n" +
	"acceptance\x18\x01 \x01(\v2\x18.pumat.v1.SignedEnvelopeR\n" +
	"acceptance\"\x1b\n" +
	"\tAckResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"@\n" +
	"\rRecordRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04pathB(Z&github.com/chaeeundad/PFCN/internal/pbb\x06proto3"

var (
	file_pumat_proto_rawDescOnce sync.Once
	file_pumat_proto_rawDescData []byte
)

func file_pumat_proto_rawDescGZIP() []byte {
	file_pumat_proto_rawDescOnce.Do(func() {
		file_pumat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pumat_proto_rawDesc), len(file_pumat_proto_rawDesc)))
	})
	return file_pumat_proto_rawDescData
}

var file_pumat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pumat_proto_goTypes = []any{
	(*SignedEnvelope)(nil),    // 0: pumat.v1.SignedEnvelope
	(*Signature)(nil),         // 1: pumat.v1.Signature
	(*Error)(nil),             // 2: pumat.v1.Error
	(*Frame)(nil),             // 3: pumat.v1.Frame
	(*CapabilityRequest)(nil), // 4: pumat.v1.CapabilityRequest
	(*LeaseRequest)(nil),      // 5: pumat.v1.LeaseRequest
	(*LeaseConfirm)(nil),      // 6: pumat.v1.LeaseConfirm
	(*InputBegin)(nil),        // 7: pumat.v1.InputBegin
	(*InputHave)(nil),         // 8: pumat.v1.InputHave
	(*Chunk)(nil),             // 9: pumat.v1.Chunk
	(*InputDone)(nil),         // 10: pumat.v1.InputDone
	(*StatusRequest)(nil),     // 11: pumat.v1.StatusRequest
	(*Status)(nil),            // 12: pumat.v1.Status
	(*ChunkRequest)(nil),      // 13: pumat.v1.ChunkRequest
	(*Ack)(nil),               // 14: pumat.v1.Ack
	(*AckResult)(nil),         // 15: pumat.v1.AckResult
	(*RecordRequest)(nil),     // 16: pumat.v1.RecordRequest
}
var file_pumat_proto_depIdxs = []int32{
	1,  // 0: pumat.v1.SignedEnvelope.signatures:type_name -> pumat.v1.Signature
	2,  // 1: pumat.v1.Frame.error:type_name -> pumat.v1.Error
	4,  // 2: pumat.v1.Frame.capability_request:type_name -> pumat.v1.CapabilityRequest
	0,  // 3: pumat.v1.Frame.capability:type_name -> pumat.v1.SignedEnvelope
	5,  // 4: pumat.v1.Frame.lease_request:type_name -> pumat.v1.LeaseRequest
	0,  // 5: pumat.v1.Frame.lease_offer:type_name -> pumat.v1.SignedEnvelope
	0,  // 6: pumat.v1.Frame.lease_countersigned:type_name -> pumat.v1.SignedEnvelope
	6,  // 7: pumat.v1.Frame.lease_confirm:type_name -> pumat.v1.LeaseConfirm
	7,  // 8: pumat.v1.Frame.input_begin:type_name -> pumat.v1.InputBegin
	8,  // 9: pumat.v1.Frame.input_have:type_name -> pumat.v1.InputHave
	9,  // 10: pumat.v1.Frame.chunk:type_name -> pumat.v1.Chunk
	10, // 11: pumat.v1.Frame.input_done:type_name -> pumat.v1.InputDone
	11, // 12: pumat.v1.Frame.status_request:type_name -> pumat.v1.StatusRequest
	12, // 13: pumat.v1.Frame.status:type_name -> pumat.v1.Status
	13, // 14: pumat.v1.Frame.chunk_request:type_name -> pumat.v1.ChunkRequest
	14, // 15: pumat.v1.Frame.ack:type_name -> pumat.v1.Ack
	15, // 16: pumat.v1.Frame.ack_result:type_name -> pumat.v1.AckResult
	16, // 17: pumat.v1.Frame.record_request:type_name -> pumat.v1.RecordRequest
	0,  // 18: pumat.v1.Frame.record_manifest:type_name -> pumat.v1.SignedEnvelope
	0,  // 19: pumat.v1.Frame.announcement:type_name -> pumat.v1.SignedEnvelope
	0,  // 20: pumat.v1.Frame.cancel:type_name -> pumat.v1.SignedEnvelope
	0,  // 21: pumat.v1.LeaseRequest.request:type_name -> pumat.v1.SignedEnvelope
	0,  // 22: pumat.v1.LeaseRequest.solver_manifest:type_name -> pumat.v1.SignedEnvelope
	0,  // 23: pumat.v1.Status.completion:type_name -> pumat.v1.SignedEnvelope
	0,  // 24: pumat.v1.Ack.acceptance:type_name -> pumat.v1.SignedEnvelope
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_pumat_proto_init() }
func file_pumat_proto_init() {
	if File_pumat_proto != nil {
		return
	}
	file_pumat_proto_msgTypes[3].OneofWrappers = []any{
		(*Frame_Error)(nil),
		(*Frame_CapabilityRequest)(nil),
		(*Frame_Capability)(nil),
		(*Frame_LeaseRequest)(nil),
		(*Frame_LeaseOffer)(nil),
		(*Frame_LeaseCountersigned)(nil),
		(*Frame_LeaseConfirm)(nil),
		(*Frame_InputBegin)(nil),
		(*Frame_InputHave)(nil),
		(*Frame_Chunk)(nil),
		(*Frame_InputDone)(nil),
		(*Frame_StatusRequest)(nil),
		(*Frame_Status)(nil),
		(*Frame_ChunkRequest)(nil),
		(*Frame_Ack)(nil),
		(*Frame_AckResult)(nil),
		(*Frame_RecordRequest)(nil),
		(*Frame_RecordManifest)(nil),
		(*Frame_Announcement)(nil),
		(*Frame_Cancel)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pumat_proto_rawDesc), len(file_pumat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pumat_proto_goTypes,
		DependencyIndexes: file_pumat_proto_depIdxs,
		MessageInfos:      file_pumat_proto_msgTypes,
	}.Build()
	File_pumat_proto = out.File
	file_pumat_proto_goTypes = nil
	file_pumat_proto_depIdxs = nil
}
